### ISSUE TITLE
Top Mud Blocks overly reflective

### ISSUE THREAD

**Issue by DomoTurbulence** [MazeWave/Vanilla-Raytraced#2]
Hey, great work on this vanilla RTX pack, it's almost perfect. I've noticed that the top mud blocks with grass on them are overly reflective on their sides. Could you possible improve this? Maybe make them less reflective, or make the full mud block more reflective? hope the image helps to show the issue. Thanks and keep up the great work!

![2020-12-15 (1)](https://user-images.githubusercontent.com/76074926/102881991-99480c00-4445-11eb-839a-67ffad9ea270.png)

**Comment by MazeWave** [comment]
Yup it's already fixed for the next version ! I've noticed that bug before and its really annoying. If you found other bug on the pack, you can open a new Issue. Thank you ! (also if you think that nether is to reflective, it will be fixed in the next update)

**Comment by MazeWave** [comment]
Fixed version :
![image](https://user-images.githubusercontent.com/25009364/102280022-b011ce80-3f2c-11eb-8fb2-cad2f0370f53.png)

**Comment by DomoTurbulence** [comment]
Hey thanks for the quick response, glad to hear the bug will be fixed!
I quite like the shiny nether, so maybe it can be 20% less shiny! you're call though obviously!

**Comment by MazeWave** [comment]
Also fixed for the upcoming update ! The shiny nether divide a lots of people, somes like me like it and other don't this i why in the next update, the nether we look normal. And for those who like the effect, there will be an Addon for that 😄
