### ISSUE TITLE
Banners have no texture

### ISSUE THREAD

**Issue by DomoTurbulence** [MazeWave/Vanilla-Raytraced#3]
Hey, another little bug, the banners in your pack seem to have no texture. See image below.

![2020-12-19 (2)](https://user-images.githubusercontent.com/76074926/102881743-35254800-4445-11eb-9e3b-0f374481718f.png)

**Comment by MazeWave** [comment]
Wow this is an interesting one ! Thank you for opening the issue, I will try to fix this 😅
