### ISSUE TITLE
Villagers lose gear related to role

### ISSUE THREAD

**Issue by DomoTurbulence** [MazeWave/Vanilla-Raytraced#4]
Hey, noticed that villagers all look the same with your pack, and they don't have their gear that related to their job role. The two images show with and without. I'm playing on realms btw.

![2020-12-17 (30)](https://user-images.githubusercontent.com/76074926/102881693-2474d200-4445-11eb-9115-92cde5ae6e64.png)
![2020-12-17 (31)](https://user-images.githubusercontent.com/76074926/102881703-28085900-4445-11eb-8602-a93b489cb4cb.png)

**Comment by 06Games** [comment]
This is a known issue due to the RTX renderer, it is listed here: [Minecraft with Ray Tracing Known Issues List ](https://help.minecraft.net/hc/en-us/articles/360042255511-Minecraft-with-Ray-Tracing-Known-Issues-List)
