### ISSUE TITLE
Conduits have no light source

### ISSUE THREAD

**Issue by DomoTurbulence** [MazeWave/Vanilla-Raytraced#5]
Hey, last one for today, sorry for all the reports, hope it helps!

Noticed that conduits don't seem to be a light source in your pack, but in the regular minecraft they are. Images below show with and without RTX.

![2020-12-17 (44)](https://user-images.githubusercontent.com/76074926/102881784-43736400-4445-11eb-9453-3427e636e24b.png)
![2020-12-17 (45)](https://user-images.githubusercontent.com/76074926/102881786-453d2780-4445-11eb-8a67-9695437e16d2.png)

**Comment by MazeWave** [comment]
It looks like Mojang forgot to add the conduit's light when ray tracing is on. I added the texture so that it can diffuse light when this is fixed in a future update of Render Dragon.
PS: Render dragon is the new engine that adds ray tracing support.
