### ISSUE TITLE
Rtx Not Working

### ISSUE THREAD

**Issue by FrostoFoxy** [MazeWave/Vanilla-Raytraced#9]
When I try to open the shader it it says that there is an error that this will get information from rtx and your device is not compatible.(I have a Radeon RX 570  Series)

**Comment by 06Games** [comment]
Hello,
This error is totally normal, as your graphics card is indeed not compatible with the RTX. You must have at least an Nvidia **GeForce RTX 20 Series** or an AMD **Radeon RX 6000 Series** card.
I strongly encourage you to read [this article](https://help.minecraft.net/hc/en-us/articles/360052769812-Minecraft-with-Ray-Tracing-Technical-Requirements) to get more information about the required configuration.

**Comment by FrostoFoxy** [comment]
thanks
